
### create account
POST http://localhost:8080/auth/register
Content-Type: application/json

{
  "areaId": 200,
  "email": "kjh19920718@gmail.com",
  "password": "123456",
  "userName": "재하",
  "phone": "010-1112-2222"
}

### login
POST http://localhost:8080/auth/login
Content-Type: application/json

{
  "email": "kjh19920718@gmail.com",
  "password": "123456"
}

### read account info
GET http://localhost:8080/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJramgxOTkyMDcxOEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjczMzUzMzg2fQ.Nx_sAXeKApF47-emC00xTrvTNVBfKUfNOvFTNll0U1GKHas44LV3aNdCa7LUVLnWHMFK4RHYnIQIp84i7AT8HQ

### change account info
PATCH http://localhost:8080/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJramgxOTkyMDcxOEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjczMzQ5ODY1fQ.XQ-8bJinjs7MPn8cYZK4TbsTG6C6ltwZRYrwzpNx2WQhAooUMWZJLotFHPI2dUGVjLguW4IxR266q8Q20eHJzA

{
  "areaId": 300,
  "userName": "jaeha123",
  "phone": "010-9999-1111"
}

### change passsword
PATCH http://localhost:8080/auth/password
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJramgxOTkyMDcxOEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjc0MjE4NzYzfQ.ma8TYuoOFOM5h_M7a40GjowSih3oTCMlY_YthOjLoQtjPaX29Lf60EvKJ4F0nYI7_2CX8KgzNOaNL91GXtuHKA

{
  "email": "kjh19920718@gmail.com",
  "password": "1234567890",
  "newPassword": "123456789"
}

### change lost passsword
PUT http://localhost:8080/auth/password
Content-Type: application/json

{
  "email": "kjh19920718@gmail.com",
  "newPassword": "1234567890"
}

### logout
DELETE http://localhost:8080/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJramgxOTkyMDcxOEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjc0MjMyNTEzfQ.vm4Rqr-vK1uZxUpeV8kgLjug-bM2NT3h1ZfNKq-j7OcBKRfzjVi-gh0mJOa27tB9tFu9OsynXdSWagcNrDUAvw

{
  "accessToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJramgxOTkyMDcxOEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjc0MjMyNTEzfQ.vm4Rqr-vK1uZxUpeV8kgLjug-bM2NT3h1ZfNKq-j7OcBKRfzjVi-gh0mJOa27tB9tFu9OsynXdSWagcNrDUAvw"
}

### delete account
DELETE http://localhost:8080/auth/
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJramgxOTkyMDcxOEBnbWFpbC5jb20iLCJhdXRoIjoiUk9MRV9VU0VSIiwiZXhwIjoxNjc0MjE4NzYzfQ.ma8TYuoOFOM5h_M7a40GjowSih3oTCMlY_YthOjLoQtjPaX29Lf60EvKJ4F0nYI7_2CX8KgzNOaNL91GXtuHKA

{
  "password": "12345678"
}

### reissue access token using refresh token
GET http://localhost:8080/auth
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJramgxOTkyMDcxOEBnbWFpbC5jb20iLCJleHAiOjE2NzU2MTQ5MTN9.4PR7zaQ921qvagFg8NXETbPTW-ELUY6r5TPUQwyEX-s28Ptg6GP0_r2_vjfdLjM4PFeTiHGWobnGssb7BjqLiA"
}


